[package]
name = "rwa_raffle_cspr"
version = "0.1.0"
edition = "2021"
description = "RWA raffle contract for Casper Network"
license = "Apache-2.0"

[lib]
name = "rwa_raffle_cspr"
crate-type = ["cdylib"]

[dependencies]
casper-contract = "5.1.1"
casper-types = "6.1.0"

[profile.release]
lto = true
opt-level = "z"
