[workspace]
members = [
  "contracts/rwa_raffle",
  "contracts/+odra_another_mint",
  "contracts/+odra_authority_mint",
]
resolver = "2"

[package]
name = "mogate-rwa-raffle-monorepo"
version = "0.1.0"
edition = "2021"

[dependencies]
ant_mint_test = { path = "contracts/+odra_another_mint" }
odra-casper-wasm-env = "2.4.0"

[[bin]]
name = "mogate_rwa_raffle_monorepo_build_contract"
path = "bin/build_contract.rs"

[profile.release]
overflow-checks = true

[workspace.package]
edition = "2021"
