use anchor_lang::prelude::*;

#[error_code]
pub enum RaffleError {
    #[msg("TotalSlotsZero")] 
    TotalSlotsZero,
    #[msg("MaxSlotsZero")] 
    MaxSlotsZero,
    #[msg("RaffleExists")] 
    RaffleExists,
    #[msg("RaffleNotFound")] 
    RaffleNotFound,
    #[msg("NotOpen")] 
    NotOpen,
    #[msg("RaffleExpired")] 
    RaffleExpired,
    #[msg("NoSlots")] 
    NoSlots,
    #[msg("OverCapacity")] 
    OverCapacity,
    #[msg("MaxSlotsPerAddress")] 
    MaxSlotsPerAddress,
    #[msg("SlotOutOfRange")] 
    SlotOutOfRange,
    #[msg("DuplicateSlot")] 
    DuplicateSlot,
    #[msg("SlotTaken")] 
    SlotTaken,
    #[msg("NothingPaid")] 
    NothingPaid,
    #[msg("NotAdmin")] 
    NotAdmin,
    #[msg("NotWinner")] 
    NotWinner,
    #[msg("NotDrawn")] 
    NotDrawn,
    #[msg("AlreadyClaimed")] 
    AlreadyClaimed,
    #[msg("BadStatus")] 
    BadStatus,
    #[msg("NotImplemented")] 
    NotImplemented,
}
