{
  metadata: [0field, 0field, 0field, 0field],
  name: [0field, 0field, 0field, 0field],
  image: [
    0field, 0field, 0field, 0field,
    0field, 0field, 0field, 0field,
    0field, 0field, 0field, 0field,
    0field, 0field, 0field, 0field
  ],
  attributes: [
    { trait_type: [0field, 0field, 0field, 0field], trait_value: [0field, 0field, 0field, 0field] },
    { trait_type: [0field, 0field, 0field, 0field], trait_value: [0field, 0field, 0field, 0field] },
    { trait_type: [0field, 0field, 0field, 0field], trait_value: [0field, 0field, 0field, 0field] },
    { trait_type: [0field, 0field, 0field, 0field], trait_value: [0field, 0field, 0field, 0field] }
  ]
}

